databases:
  - name: royaldryfruits-db
    databaseName: royaldryfruits
    plan: free

services:
  - type: web
    name: royaldryfruits-api
    env: docker
    region: singapore
    plan: free
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: royaldryfruits-db
          property: connectionString

  - type: web
    name: royaldryfruits-storefront
    env: static

    buildCommand: cd frontend/royaldryfruits-app && npm install --include=dev && npm run build
    staticPublishPath: frontend/royaldryfruits-app/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://royaldryfruits-api.onrender.com/api

  - type: web
    name: royaldryfruits-admin
    env: static

    buildCommand: cd frontend/admin-portal && npm install --include=dev && npm run build
    staticPublishPath: frontend/admin-portal/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://royaldryfruits-api.onrender.com/api
