/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#001e2e",
        "inverse-surface": "#2d3133",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#301400",
        "surface-tint": "#944a00",
        "primary-container": "#e67e22",
        "secondary-container": "#d5e0f8",
        "outline-variant": "#dcc1b1",
        "on-background": "#191c1e",
        "secondary-fixed": "#d8e3fb",
        "on-secondary-container": "#586377",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "error-container": "#ffdad6",
        "surface": "#f7f9fb",
        "on-surface-variant": "#564337",
        "surface-bright": "#f7f9fb",
        "primary-fixed": "#ffdcc5",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#86cfff",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-fixed-variant": "#004c6d",
        "secondary-fixed-dim": "#bcc7de",
        "on-primary-fixed-variant": "#713700",
        "tertiary-fixed": "#c7e7ff",
        "inverse-primary": "#ffb783",
        "inverse-on-surface": "#eff1f3",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#ffb783",
        "on-error-container": "#93000a",
        "tertiary": "#00658f",
        "surface-dim": "#d8dadc",
        "secondary": "#545f73",
        "on-surface": "#191c1e",
        "on-primary": "#ffffff",
        "tertiary-container": "#00a3e4",
        "primary": "#944a00",
        "outline": "#897365",
        "on-primary-container": "#502600",
        "background": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "surface-variant": "#e0e3e5",
        "on-secondary-fixed-variant": "#3c475a",
        "on-tertiary-container": "#00354d",
        "on-secondary-fixed": "#111c2d"
      },
      spacing: {
        "sm": "16px",
        "sidebar-width": "260px",
        "md": "24px",
        "max-content-width": "1440px",
        "lg": "32px",
        "xs": "8px",
        "base": "4px",
        "xl": "48px"
      },
      fontFamily: {
        body: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
